server:
  port: 9002
spring:
  application:
    name: service-oss
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

#aliyun configuration
# ?????????? '='??????????????
aliyun:
  oss:
    file:
      endPoint: oss-cn-shanghai.aliyuncs.com


# ????????